hexojs/hexo-util

lib/highlight.js
To add a new feature disable highlight auto-detect.
See the issue from [hexo  #1224](https://github.com/hexojs/hexo/issues/1224)
=> [New Feature]Add parameter to disable highlight auto-detect.

lib/highlight.js, test/scripts/highlight.js
=> give 'marked' class to marked lines

README.md
=> docs: Added highlight config documentation for 'hljs'.

.npmignore
See https://unpkg.com/hexo-util@0.6.3/
I was unsure about https://unpkg.com/hexo-util@0.6.3/highlight_alias.json
should it be removed or not ?
=> remove useless file from npm module

lib/index.js, package.json
I also sort the functions in alphabetical order
=> release: 1.0.1

README.md
Feature added in https://github.com/hexojs/hexo-util/pull/77
=> docs: add encodeURL()

README.md, test/url_for.spec.js
also update test to be more obvious on the override option
Closes #87
=> docs: url_for option

package.json
to include https://github.com/hexojs/hexo-util/pull/101 #102
=> release: 1.3.1

README.md, lib/html_tag.js, test/html_tag.spec.js
Intend to use this feature in https://github.com/hexojs/hexo/pull/3681 & https://github.com/hexojs/hexo/pull/3690.
=> feat(htmlTag): support async/defer attribute

package.json
=> release: 1.4.0

lib/escape_html.js, lib/unescape_html.js, test/escape_html.spec.js, test/unescape_html.spec.js
https://github.com/janl/mustache.js/blob/9452eafd642c7bf827fa0627bd493e1fdf48da94/mustache.js#L74-L81
Also added to `unescapeHTML()`.
=> fix(escape_html): escape equal sign

package.json
Bump minor (instead of patch) due a minor breaking change introduced in https://github.com/hexojs/hexo-util/pull/130
=> release: 1.6.0

lib/full_url_for.js, lib/url_for.js, test/full_url_for.spec.js, test/url_for.spec.js
=> fix(url_for/full_url_for): should be config.pretty_urls

package.json
https://github.com/hexojs/hexo-util/pull/143
=> release: 1.6.1

package.json
emergency fix #153 plus some features
=> release: 1.7.0

lib/color.js, lib/decode_url.js, lib/encode_url.js, lib/unescape_html.js, package.json, test/highlight.spec.js
Supersedes and closes https://github.com/hexojs/hexo-util/pull/148
=> style: eslint-config-hexo@4

test/highlight.spec.js
Part of https://github.com/hexojs/hexo/pull/3976
=> test(highlight): comment out empty test

README.md, lib/index.js, lib/prism.js, package.json, test/prism.spec.js
Related to https://github.com/hexojs/hexo/issues/1036  https://github.com/hexojs/hexo/issues/4010
=> feat: bring up prism highlight support

.github/release-drafter.yml, .github/workflows/release-drafter.yml
Please see following issue.
> https://github.com/hexojs/hexo/issues/3858
I tested my repository before submitting PR. Please see the following. The following example settings are same with this PR.
> https://github.com/YoshinoriN/TestRepository/releases/tag/v3.0.2
=> chore: add release release-drafter

package.json
=> release: 1.9.0

.github/release-drafter.yml
- easier conversion to news post
``` md
- chore(deps-dev): bump rewire from 4.0.1 to 5.0.0 @dependabot-preview [#187]
[#187]: https://github.com/hexojs/hexo-util/pull/187
```
=> chore(release-drafter): wrap pull-request reference in square bracket

package.json
~~Pending: https://github.com/hexojs/hexo-util/pull/205~~
This PR for hexo v4.2.1
> https://github.com/hexojs/hexo/pull/4285
Target branch is `1.9.1`
I will release `1.9.1` after merge this PR.
=> chore: release v1.9.1

test/highlight.spec.js
=> test(highlight): fix test cases

package.json
https://github.com/hexojs/hexo-util/pull/225
=> release: 2.3.0

package.json
I'm going to release a new version after merge this PR.
Thank you :)
=> chore: bump version from 2.5.0 to 2.6.0

package.json
I'm going to publish a new version after merge this PR.
Thank you :)
=> chore: bump version from 2.6.0 to 2.6.1

package.json
Included #278, #277
I'm going to publish a new version after merge this PR.
Thank you :)
=> release 2.7.0

lib/spawn.ts, package.json
refs: https://github.com/hexojs/hexo-util/pull/267
=> refactor: use native promise instead of bluebird

lib/cache.ts, lib/html_tag.ts, lib/permalink.ts, lib/relative_url.ts, lib/url_for.ts
Fix type issues found with https://github.com/hexojs/hexo/pull/5092
=> fix inaccurate types

test/color.spec.js, test/decode_url.spec.js, test/is_external_link.spec.js, test/pattern.spec.js, test/permalink.spec.js, test/spawn.spec.js, test/strip_indent.spec.js
https://github.com/hexojs/hexo/issues/3984
=> test: improve coverage

SECURITY.md
=> chore(SECURITY): Create SECURITY.md

lib/html_tag.ts
see https://developer.twitter.com/en/docs/twitter-for-websites/cards/overview/player-card
=> feat(html_tag): support twitter:player

package.json
=> chore: fix ghost dependency

scripts/build_highlight_alias.js
As the title.
This will make it a little bit faster
=> feat(scripts): use hljs internal method to get aliases

package.json
We need a new version for https://github.com/hexojs/hexo/pull/5427
fix #401
=> release: v3.3.0

lib/encode_url.ts, test/encode_url.spec.ts
a way to fix hexojs/hexo-renderer-marked#268
=> feat(encodeUrl): encode pathname

.github/workflows/linter.yml, .github/workflows/tester.yml, package.json
=> require node version lt 18
