lib/truncate.js
test/scripts/truncate.js

With this fix the function truncate is more generic. It handles cases when the string length is shorter than the truncate length in that case omission characters should not be added since they are displaying in full.

truncate: fixes handling strings shorter than truncate length

---

lib/highlight.js
package.json
test/scripts/highlight.js

Correct highlighting of multi-line element (fix #10 and hexojs/hexo#2291).
This patch is similar to the patch hexojs/hexo#904 that fixed the issue hexojs/hexo#902.
But the API `highlightByLine()` is no longer supported by [highlight.js](http://highlightjs.readthedocs.io/en/latest/api.html).
So I use the API `highlight()` with continuation.
And also add HTML validation to each test case.
If this validation was implemented, the issue #10 might be detected.
For this puropose, add a new `devDependencies` for `html-tag-validator` package.    
https://www.npmjs.com/package/html-tag-validator    
https://github.com/codeschool/htmlTagValidator

BugFix: Correct highlighting of multi-line element (fix #10 and hexojs/hexo#2291)

---

lib/highlight.js
test/scripts/highlight.js

For some reason I changed the spans to divs in a PR six months ago. Here's the fix to get rid of those divs again. Thanks to @csarron for letting me know the issue

change divs in code blocks back to spans

---

.npmignore
.travis.yml
CHANGELOG.md
package.json

Use a `prepare` hook instead of a `postinstall` hook to generate
the `highlight_alias.json` file. This means that the file is generated
during the publication of package to npm or when manually running
`npm install` in the project directory.
The previous behavior was to generate this step on the consumer
side: this was the cause of numerous hard-to-reproduce issues due
to the variety of environments.
Closes hexojs/hexo-util#20
Closes hexojs/hexo-util#23
Closes hexojs/hexo-util#24
Related to hexojs/hexo-cli#23
Related to hexojs/hexo#2095

Remove postinstall step

---

lib/highlight.js
test/scripts/highlight.js

This pull request adds additional support to render the highlighting with `hljs-` prefix and preserves backward compatibility for existing themes/stylesheets.
Support for both marked lines and line numbers, as well as vanilla highlight.js blocks is included.
This is a quick proof of concept that I whipped up after I started working on my theme and realizing that hljs CSS themes weren't supported. I hope it can be helpful to hexo users.
It's a two part pull request as [hexo/#2901](https://github.com/hexojs/hexo/pull/2901) adds support for propagating the `hljs` configuration through to the highlight plugin.
If everything is good (or after necessary changes), I will be updating the documentation as well to document the new config for `_config.yml`.
Cheers,

hljs - Added compatibility for CSS styles.

---

lib/html_tag.js
test/scripts/html_tag.js

Fixes this issue -> https://github.com/hexojs/hexo/issues/3222

Allows empty attributes in html tag helper

---

test/index.js
test/scripts/cache_stream.js
test/scripts/camel_case_keys.js
test/scripts/escape_diacritic.js
test/scripts/escape_html.js
test/scripts/escape_regexp.js
test/scripts/hash.js
test/scripts/highlight.js
test/scripts/html_tag.js
test/scripts/pattern.js
test/scripts/permalink.js
test/scripts/slugize.js
test/scripts/spawn.js
test/scripts/truncate.js
test/scripts/word_wrap.js

This PR is divided PR because #35 has become big.

Refactoring test: es2016nify

---

lib/cache_stream.js
lib/camel_case_keys.js
lib/escape_diacritic.js
lib/escape_html.js
lib/hash.js
lib/highlight.js
lib/html_tag.js
lib/index.js
lib/pattern.js
lib/permalink.js
lib/slugize.js
lib/spawn.js
lib/truncate.js
lib/word_wrap.js

This PR is divided PR because #35 has become big.

Refactoring es2016nify

---

README.md
lib/hash.js
test/scripts/hash.js

This PR is divided PR because #35 has become big.
`Hash` class It itself inherits the `Transform` class. There is no need to go through `HashStream`.
In addition, `HashStream` implementation does not assume `objectMode`, and `objectMode` is invalid in `Transform` options! (It is controlled by `readableObjectMode` and `writableObjectMode`)
Since the implementation was originally unclear, you can solve the problem by creating a new `createSha1Hash()` and migrating it to it.

Deprecated hashStream

---

.travis.yml
lib/highlight.js
lib/permalink.js
package.json
test/scripts/spawn.js

Last version of eslint does not support nodejs 6

Bump Eslint & drop nodejs 6

---

lib/highlight.js

firstLine variable sometimes can be parsed as a string.
let say, `firstLine = 1`; `firstLine + 3` can results in `13`, instead of expected `4`.
See https://github.com/hexojs/hexo/pull/3646

fix: prevent firstLine being parsed as a string

---

lib/color.js
test/index.js
test/scripts/color.js

`tagcloud` helper depends on the `Color` inner class. This class is reusable but is not currently tested alone.
Therefore, after porting to `hexo-util`, we separate tagcloud-dependent code from the original test. This improves the maintainability.
```
$ git clone https://github.com/segayuu/hexo-util
$ cd hexo-util
$ git fetch
$ git checkout Add-Color
```
```
$ npm install
$ npm run test
```
https://github.com/hexojs/hexo/blob/3.8.0/lib/plugins/helper/tagcloud.js
https://github.com/hexojs/hexo/blob/3.8.0/test/scripts/helpers/tagcloud.js

Add Color class from tagcloud hexo helper

---

package.json
scripts/build_highlight_alias.js

in some edge case, stdout can [be empty](https://stackoverflow.com/questions/54190596/no-console-log-to-stdout-when-running-npm-test-jest) when running npm script, i.e. `npm run prepare`. `fs.write` is more reliable.
"highlight_alias.json" should be published, it's generated when `npm publish`. The value in "files" attribute is needed even when `"hexo-util": "hexojs/hexo-util"`, otherwise it would not be generated when `npm install`.
Fixes https://github.com/hexojs/hexo/pull/3646#issuecomment-519465750, Address https://github.com/hexojs/hexo-util/pull/57#issuecomment-519031638
`$ rm -r node_modules/`
``` diff
package.json
-  "hexo": "^3.9.0"
+  "hexo": "curbengh/hexo#rc"
```
``` bash
$ npm i
$ hexo -v # should be no error
$ npm test
```

fix: fs.write instead of stdout

---

lib/highlight.js
test/scripts/highlight.js

Highlightjs has a sublanguages feature which allows some languages to incorporate and highlight another language inside it. When I use a sublanguage in Hexo, it doesn't work:
This PR make the sublanguages functional:
The sublanguage feature requires that the sublangage definition is loaded. But Hexo only load the definition of the main language of the code chunk. I suggest to always load all language definitions, like it's done in highlightjs library and in hexo-util tests (so the tests are currently not totally right since the definitions loaded in tests are not the same as the definitions actually loaded by hexo-utils).
Also, it could be possible to dynamically load sublanguages but it will make hexo-util too closely coupled with hightlighjs IMHO.

Fix sublanguages highlight

---

lib/index.js

Currently, using the Color function requires `const Color = require('../../../node_modules/hexo-util/lib/color');`.
It should be just `const Color = require('hexo-util').Color;`.

fix: export Color function

---

lib/encode_url.js
lib/index.js
test/encode_url.spec.js

This PR is stemmed from IDN parsing issue (https://github.com/hexojs/hexo-generator-feed/issues/63). It was later (partially) fixed in https://github.com/hexojs/hexo-generator-feed/pull/82, without encodeURI the root value. Full fix is later proposed in https://github.com/hexojs/hexo-generator-feed/pull/88.
IDN incompatibility is also found in [hexo-generator-sitemap](https://github.com/hexojs/hexo-generator-sitemap/pull/66) and [open_graph()](https://github.com/hexojs/hexo/pull/3686).
All the proposed fixes actually share similar function, so I propose to put it in hexo-util instead.

feat: add encodeURL()

---

lib/encode_url.js
test/encode_url.spec.js

fix: handle url with hash, query, auth and port

---

README.md
lib/full_url_for.js
lib/index.js
test/full_url_for.spec.js

https://github.com/hexojs/hexo/pull/3701

feat(full_url_for): bring up a new helper

---

README.md

forgot to close the codeblock.
also update docs that `relative:` also works the other around.

fix: readme codeblock

---

README.md
lib/html_tag.js
test/html_tag.spec.js

Related to https://github.com/hexojs/hexo/pull/3704 (cc @dailyrandomphoto)
This is to transform
``` html
<a href="/posts/test1/" title="this is a title with <a tag>.">this is a text with </a><a tag="">.</a>
```
to
``` html
<a href="/posts/test1/" title="this is a title with &lt;a tag&gt;.">this is a text with &lt;/a&gt;&lt;a tag=""&gt;.</a>
```
There is an option to disable escape _just_ the text.
``` js
htmlTag('a', {href: 'http://foo.com'}, '<b>bold</b> text', false)
```
``` html
<a href="http://foo.com"><b>bold</b> text</a>
```

fix(html_tag): escape html and encode url by default

---

lib/encode_url.js
test/encode_url.spec.js

with #92 
In some edge case, decode a text which is not encoded by `encodeURI`, `decodeURI` will raise `URI malformed` exception.
e.g.
```js
encodeURL("http://foo.com/bar?query=%");
encodeURL("/bar?query=%");
```
```
URIError: URI malformed
at decodeURI (<anonymous>)
at encodeURL (lib/encode_url.js:25:20)
```
Use `try, catch` can prevent this exception.

prevent 'URI malformed' exception

---

README.md
lib/decode_url.js
lib/index.js
lib/punycode.js
test/decode_url.spec.js

Decode [encoded](https://en.wikipedia.org/wiki/Percent-encoding) URL or path. An alternative to the native [`decodeURI()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/decodeURI) function, with added ability to decode [punycoded](https://en.wikipedia.org/wiki/Punycode) domain.
lib/punycode.js is derived from https://github.com/bestiejs/punycode.js with `punycode.toUnicode(input)` function only and some minor modifications to pass eslint-config-hexo. It's not added in index.js as it shouldn't be used outside of hexo.

feat: decodeURL()

---

README.md
lib/html_tag.js
test/html_tag.spec.js

address https://github.com/hexojs/hexo-util/pull/94#issuecomment-531865496 to support url value in data-* attributes (e.g. data-url, [`data-src`](https://cloudinary.com/documentation/responsive_images#step_2_set_the_img_tag_parameters))
cc @dailyrandomphoto
test case is already covered by
``` js
it('encode url', () => {
htmlTag('img', {
src: 'http://foo.com/bár.jpg'
}).should.eql('<img src="http://foo.com/b%C3%A1r.jpg">');
});
```

fix(html_tag): encode url value of url-related attributes and skip escape/encode <style>

---

README.md

Noticed while working on https://github.com/hexojs/site/issues/1085

docs: override example should be consistent with example config

---

README.md
lib/html_tag.js
test/html_tag.spec.js

Continuation of https://github.com/hexojs/hexo-util/pull/96#discussion_r326639896
Regex is based on [`external_link.js`](https://github.com/hexojs/hexo/blob/master/lib/plugins/filter/after_post_render/external_link.js)

fix(html_tag): encode url() in style tag

---

package.json

to include #92 #93 #97 #96 #100 #101 
note #93 is a possible breaking change, for an edge case like `<a href="foo.com"><b>text</b></a>`.

release: 1.3.0

---

lib/encode_url.js
lib/html_tag.js
test/encode_url.spec.js

`url.parse(str).slashes` is used to avoid treating `mailto:` as a transfer protocol (e.g. http, ftp).
``` js
const { parse } = require('url')
console.log(parse('mailto:abc@example.com'))
/*
Url {
protocol: 'mailto:',
slashes: null,
auth: 'abc',
host: 'example.com',
port: null,
hostname: 'example.com',
hash: null,
search: null,
query: null,
pathname: null,
path: null,
href: 'mail:abc@example.com'
}
*/
```
This avoids `null` from being appended undesirably.
---
- Expected behavior
``` js
encodeURL('mailto:abc@example.com')
// mailto:abc@example.com
```
- Actual behavior 
``` js
encodeURL('mailto:abc@example.com')
// mailto:abc@example.comnull
```
Address https://github.com/hexojs/hexo/pull/3710#issuecomment-533863007

fix(encode_url): skip encode non-urls

---

README.md
lib/escape_html.js
lib/index.js
lib/unescape_html.js
test/escape_html.spec.js
test/unescape_html.spec.js

Noticed an edge case where ampersand `&` is escaped twice, while working on https://github.com/hexojs/hexo/pull/3686 which I had to use [this workaround]( https://github.com/hexojs/hexo/pull/3686/files#diff-c4a1a49a7c6ed5695f830ccde3a217c3).

feat: add unescapeHTML() & fix(escapeHTML): avoid double escape

---

README.md

some html tag requires a closing tag, in which case an empty string can be added as the third argument. (Edit: I moved the example to https://github.com/hexojs/hexo-util/pull/106)
`Function.call()` is based on [`full_url_for()`](https://github.com/hexojs/hexo/pull/3701/files#diff-c03d9d0d457e77e7c57b00f842473d49)

docs: Function.call() examples

---

README.md

this is necessary as we migrate more helpers to hexo-util.

docs: add table of contents

---

README.md

This is what I would've implemented in https://github.com/hexojs/hexo-util/pull/114, if not for the bug in Node 8.

docs(decodeURL): add native API example

---

lib/decode_url.js
lib/encode_url.js
lib/full_url_for.js
lib/url_for.js
test/decode_url.spec.js
test/encode_url.spec.js
test/full_url_for.spec.js
test/url_for.spec.js

legacy URL api has been deprecated in Node v11; while the API is still available in Node 12, `eslint-plugin-node` considers it as a deprecated api, thus will emit error if detected.
WHATWG url is actually introduced back in Node v7, thus contrary to my previous PR (https://github.com/hexojs/eslint-config-hexo/pull/19), it is supported in Node 8. The only thing is that Node 8 requires `const {URL} = require('url')`, whereas newer Node doesn't.
Another noticeable difference is that WHATWG remove the port number if it corresponds to the protocol (e.g. `http`:`80`, `https`:`443`), which explains the change of port number in the unit test.
`decode_url` is not refactored to the newer API for now due to a bug in Node 8,
``` js
const {format} = require('url')
const bob = new …
```

refactor: whatwg url api

---

lib/decode_url.js

Continuation of #114 
Node 8's `url.format()` doesn't support port number, so a workaround is used instead.

refactor(decodeURL): update to whatwg api

---

lib/highlight.js
test/highlight.spec.js

Fix #111
This patch is fix the behavior of `highlight()` with a option `wrap: false`.
If `hljs: false`, the output of `highlight()` should include a HTML class name `highlight`.
It is consistent with the case of `hljs: true`.
And also, even if `hljs: false`, the output of `highlight()` should be include a PRE element and a CODE element.
It is consistent with the case of `hljs: true`, too.

Make consistency in output of "highlight()" for "wrap: false" (fix #111)

---

README.md
lib/encode_url.js
test/encode_url.spec.js

Because IDN only contain unicode, they do not need to be punycode encoded.
(I bought one, I want the nice version, not the ugly one)
See https://nodejs.org/docs/latest/api/url.html#url_url_format_url_options

Leave IDN intact in permalink

---

lib/full_url_for.js
lib/url_for.js
test/full_url_for.spec.js
test/url_for.spec.js

Continuation of https://github.com/hexojs/hexo-util/pull/124
Ref: https://github.com/hexojs/hexo/issues/3846

perf: utilize legacy url.parse() in url_for() & full_url_for()

---

lib/highlight.js
package.json

Fix #127. Use hexo-util's built-in `escapeHTML()` to replace `node-html-entities`, while retains `node-html-entities` in unit-test to make sure the behaviors of highlight remain unchanged after this PR.

refactor: relpace node-html-entities with escapeHTML()

---

README.md
lib/is_external_link.js
test/is_external_link.spec.js

The PR fixes #123 with a simpler way. This PR also includes the changes from https://github.com/hexojs/hexo/pull/3839 , which is a poc of performance improvements.

refactor(isExternal): avoid undefined & improve performance

---

lib/decode_url.js
lib/encode_url.js

Part of https://github.com/hexojs/hexo/issues/3846
TL;DR
``` js
try {
return new URL(str);
} catch (err) {
return str;
}
```
is expensive.

perf(encode/decodeURL): use legacy url.parse() to avoid try...catch()

---

lib/highlight.js
test/highlight.spec.js

```html
<tr>
<td class="gutter"><pre>
<span class="line">1</span>
<br>
<span class="line">2</span>
<br>
<span class="line">3</span>
</pre></td>
<td class="code"><pre>
<span class="line">hello, world</pre>
<br>
<span class="line">hello, world</span>
<br>
<span class="line">hello, world</span>
</pre></td>
</tr>
```
```html
<tr>
<td class="gutter"><pre>
<span class="line">1</span>
</pre></td>
<td class="code"><pre>
<span class="line">hello, world</pre>
</td>
</tr>
<tr>
<td class="gutter"><pre>
<span class="line">2</span>
</pre></td>
<td class="code"><pre>
<span class="line">hello, world</pre>
</td>
</tr>
<tr>
<td class="gutter"><pre>
<span class="line">3</span>
</pre></td>
<td class="code"><pre>
<span class="line">hello, world</pre>
</td>
</tr>
```

feat(highlight): adjust the layout of the highlight code block

---

lib/full_url_for.js
lib/url_for.js
test/full_url_for.spec.js
test/url_for.spec.js

Fixes #122 
BREAKING CHANGE: drop support for pathname with semicolon
cc @lookis

fix(url_for & full_url_for): ignore data url

---

README.md

Notice missing docs while working on https://github.com/hexojs/hexo/pull/3848

docs(highlight): 'mark' option

---

README.md
lib/is_external_link.js
test/is_external_link.spec.js

In order to better utilizing `isExternalLink()`, this PR makes `isExternalLink()` no longer requires `bind(hexo)`. `sitehost` & `exclude` will need to be passed after this PR.
**Affected code:**
https://github.com/hexojs/hexo/pull/3835, https://github.com/hexojs/hexo/pull/3847: New parameters will be needed.
[hexo-filter-nofollow](https://github.com/hexojs/hexo-filter-nofollow), https://github.com/hexojs/hexo-renderer-marked/pull/116, https://github.com/hexojs/hexo-renderer-marked/pull/119: `hexo-filter-nofollow` and `hexo-renderer-marked` will be able to utilize `isExternalLink()`.

refactor(isExternallink): no longer needs bind(hexo)

---

lib/permalink.js
test/permalink.spec.js

Fix issue hexojs/hexo#3862
In `_config.yml`, the item `new_post_name:` takes a template string which includes placeholders.
The placeholders are such as `:title`, `:year`, `:i_day`.
The name of placeholders consists of alphanumeric characters and underscores.
But the last character should not be an underscore.
That is, trailing underscores of a placeholder should not be parsed as a part of the placeholder.
This patch fixes the RegExp to parse a placeholder.

Fix parsing placeholder with trailing underscore at "new_post_name"

---

lib/full_url_for.js
lib/url_for.js
test/full_url_for.spec.js
test/url_for.spec.js

I have noticed `url_for` & `full_url_for` will not remove `index.html` while `trailing_index` is disabled. This PR is addressed to make the `trailing_index` behavior more consistent. 
I haven't apply pretty_url options to `relative_url()` yet because relative_url doesn't require `bind(hexo)` and can not read `hexo.config` directly. After we finish `relative_url()` I will make this PR "Ready to Review".

feat: apply pretty_url to url_for & full_url_for

---

lib/full_url_for.js
lib/url_for.js
test/full_url_for.spec.js
test/url_for.spec.js

Noticed an edge case while testing https://github.com/hexojs/hexo-renderer-marked/pull/124
``` js
const ctx = {
config: {
url: 'http://example.com',
root: '/goal/'
}
}
console.log(url_for.call(ctx, 'http://example.com/hash/bob.html'))
// /goal/http:/example.com/hash/bob.html
```
---
`ReExp.test()` is slightly faster than `String.startsWith()/String.endsWith()` and easier to add a new pattern.

fix(url_for/full_url_for): do not process absolute url

---

README.md
lib/deep_merge.js
lib/index.js
package.json
test/deep_merge.spec.js

Continuation of https://github.com/hexojs/hexo/pull/3880

feat(deepMerge): bring up

---

lib/highlight.js
test/highlight.spec.js

Currently, enabling `hljs` always disable `wrap`, but I noticed that it is actually not necessary. I tested `hljs: true` + `wrap: true` with [darcula theme](https://github.com/highlightjs/highlight.js/blob/master/src/styles/darcula.css), code highlighting works fine.
Noticed while testing https://github.com/hexojs/hexo/pull/3865
---
``` yml
line_number: true # or gutter: true
hljs: true
wrap: false
```
Since enabling `line_number` will also enable `wrap`, this behavior doesn't change.
---
``` yml
line_number: false
hljs: true
wrap: true
```
With this PR, it is possible to enable both `hljs` and `wrap`, so user can use `hljs-*` prefix in css classes while wrapping the codeblock in `<table>`. This can make upgrading the hljs syntax slightly easier.

fix(highlight): decouple 'wrap' and 'hljs'

---

lib/highlight.js
test/highlight.spec.js

In this PR I just simply revert #132 because #132 introduces just too much Breaking Changes, see discussion at https://github.com/hexojs/hexo-util/pull/132 and related issue #145. 
IMHO, we should not bring any style changes in highlightjs any more. It will break too much things, especially when we are going to deprecate highlightjs and bring up prismjs.
Hexo has nearly 300 themes, "NexT theme works fine" is just not an enough excuse.
cc @jiangtj @stevenjoezhang @ppoffice

revert: feat(highlight): adjust the layout of the highlight code block

---

lib/html_tag.js
test/html_tag.spec.js

While working on https://github.com/hexojs/hexo/pull/3983, I found url in open graph or twitter card tag is html-escaped instead of url-encoded.

fix(html_tag): encode urls in meta tag

---

README.md
lib/cache.js
lib/full_url_for.js
lib/gravatar.js
lib/index.js
lib/is_external_link.js
lib/relative_url.js
lib/url_for.js
test/cache.spec.js

Context: #158 
Cache with plain object.
cc @dailyrandomphoto @seaoak

feat(cache): plain object cache

---

package.json

mainly to release https://github.com/hexojs/hexo-util/pull/137 required by https://github.com/hexojs/hexo/pull/3850

release: 1.8.0

---

lib/toc_obj.js
test/toc_obj.spec.js

tocObj currently crashes hexo if the heading doesn't have `id` attribute, e.g. `<h1>Title 1</h1>`. This PR makes it more robust.
With this PR, in relation to the [`toc()`](https://github.com/hexojs/hexo/blob/f50821c596a9c3a53619cbb846509e6071a1780d/lib/plugins/helper/toc.js#L50) helper, it would output
```
<a class="header-link" href="#null">
```
obviously anchor link wouldn't work, but at least there is a toc.

fix(tocObj): avoid checking length of null

---

README.md
lib/highlight.js
lib/index.js
lib/strip_indent.js
package.json

During writing proposal at https://github.com/hexojs/hexo/issues/4010, I noticed `strip-indent` is used at `hexo-renderer-marked` and [`backtick_code` filter](https://github.com/hexojs/hexo/blob/master/lib/plugins/filter/before_post_render/backtick_code_block.js).
Although `strip-indent` at `hexo-renderer-marked` will be removed in https://github.com/hexojs/hexo-renderer-marked/pull/134, but after [searching `strip-indent` at `hexojs/hexo`](https://github.com/hexojs/hexo/search?q=strip-indent&unscoped_q=strip-indent) I found `strip-indent` mostly used for highlight in `hexojs/hexo` as well. It means we should add `strip-indent` inside `highlightUtils`.
After this PR is merged, `strip-indent` inside `hexojs/hexo` could be removed.

refactor(highlight): add strip-indent

---

README.md
lib/prism.js
test/prism.spec.js

Related documents:
- `firstLine`: https://prismjs.com/plugins/line-numbers/
- `mark`: https://prismjs.com/plugins/line-highlight/

feat(prism): add mark & firstLine option support

---

lib/html_tag.js
test/html_tag.spec.js

Fixed crash when entering a numerical value into `fb_app_id` of` open_graph` helper.
Facebook app_id is a numeric string, but if it is set in `_config.yml` without quotes, the yml parser will recognize it as number.
1.8.0 and later versions crashed if the value was set to number.

htmlTag - toString() before match() for scalar values.

---

lib/prism.js
test/prism.spec.js

Add `data-language` attribute to `<pre>` tag.
It is necessary to have `data-language` attribute to be compatible with Prism's `Show Languages` Plugin: https://prismjs.com/plugins/show-language/
Besides that, with this attribute theme developer can even show current language without that plugin as well:
``` css
pre::before {
color: #bcc3ce;
content: attr(data-language); /* This looks important */
font-size: .7rem;
position: absolute;
right: .4rem;
top: .1rem;
}
```
will resulted in (The `HTML` string on top of the right):

feat(prism): add data-language attribute

---

lib/highlight.js

I found that the highlighting is incorrect when options.hljs=true.
It should use the `tryHighlight` function instead, which handles multi-line codeblock.

Fix highlighting when hljs=true

---

lib/toc_obj.js
test/toc_obj.spec.js

Fixes https://github.com/hexojs/hexo-util/issues/174 Closes https://github.com/hexojs/hexo-renderer-markdown-it/issues/102
Permalink (in this context) is a single non-word character, word = [a-Z0-9], and wrapped in `<a>`.
It may be wrapped in whitespace(s)
Scenario | Input | Output (text) | Explanation
--- | --- | --- | ---
1 | `<h1 id="foo"><a>#</a>bar</h1>`<br><br>`<h1 id="foo">bar<a>#</a></h1>`<br><br>`<h1 id="foo"><a>#</a>bar<a>#</a></h1>` | `bar`<br><br>`bar`<br><br>`bar` | `#` is treated as a permalink and skipped
2 | `<h1>号码<a>牌</a></h1>` | `号码` | `牌` is treated as a permalink
3 | `<h1><a>#</a></h1>` | `#` | If there is only permalink, parse it
4 | `<h1><a>b</a> two</h1>` | `b two` | `b` is not a permalink
---
returns empty string `''` instead of null. This is following convention. …

fix(tocObj): skip permalink symbol 

---

lib/prism.js
test/prism.spec.js

Adding `stripIndent()` for prism highlight as well as highlightjs:
https://github.com/hexojs/hexo-util/blob/7e5633a229202c3c4fc130bf61784af0d5ad44ef/lib/highlight.js#L10

fix(prism): add strip_indent support

---

lib/full_url_for.js
lib/is_external_link.js
lib/url_for.js
test/is_external_link.spec.js

Details can be found at https://github.com/hexojs/hexo/issues/4130
This PR introduce a try block and treat invalid URL as internal link (return `false`).

fix(is_external_link): handle invalid url

---

.travis.yml

smaller scope than https://github.com/hexojs/hexo-util/pull/191, affects travis only.
mainly to debug https://github.com/hexojs/hexo/issues/4260.

ci(travis): drop Node 8 and add Node 14

---

lib/cache_stream.js
test/cache_stream.spec.js

fix compatibility with Node 14
https://github.com/hexojs/hexo/issues/4260#issuecomment-618483486

fix: avoid overriding Transform.destroy() method

---

README.md

breaking change introduced by highlight.js v10 https://github.com/hexojs/hexo-util/pull/192.

docs(highlight): 'sublanguage highlight' requirement

---

README.md
lib/hash.js
test/hash.spec.js

this finally drops `HashStream()` which has been long deprecated since https://github.com/hexojs/hexo-util/pull/45.

feat(hash): drop HashStream()

---

lib/full_url_for.js
test/full_url_for.spec.js

When a markdown document have links which start with "http://", then will get Invalid URL error in `hexo generate` or `hexo server` command, such as:
```
ERROR Process failed: _posts/test.md
TypeError [ERR_INVALID_URL]: Invalid URL: http://
at onParseError (internal/url.js:257:9)
at new URL (internal/url.js:333:5)
at new URL (internal/url.js:330:22)
at /Users/jason/Documents/blog_store/node_modules/hexo-util/lib/full_url_for.js:22:18
at Cache.apply (/Users/jason/Documents/blog_store/node_modules/hexo-util/lib/cache.js:27:46)
at Hexo.fullUrlForHelper (/Users/jason/Documents/blog_store/node_modules/hexo-util/lib/full_url_for.js:18:16)
at Hexo.module.exports (/Users/jason/Documents/blog_store/node_modules/hexo/lib/plugins/helper/full_url_for.js:5:23)
at _Document.<anonymous> …
```

fix bug when parse url start with http://

---

lib/full_url_for.js
test/full_url_for.spec.js

Merged caused by mistake.
`config.url` should always be configured. Throwing error is desired behavior and must be retained.

Reverts hexojs/hexo-util#204

---

README.md
lib/cache.js
test/cache.spec.js

> (Map) Performs better in scenarios involving frequent additions and removals of key-value pairs. (While Object is) Not optimized for frequent additions and removals of key-value pairs.
>
> Objects vs. Maps, [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map)
`cache#dump` & `cache#size` is also implemented.

feat/refactor(cache): use Map, cache#dump, cache#size

---

lib/highlight.js
test/highlight.spec.js

Add codeblock caption/title even when `wrap` is disabled.
\`\`\` js title
console.log('foo');
\`\`\`
https://hexo.io/docs/tag-plugins#Examples-1
```
{% codeblock Array.map %}
array.map(callback[, thisArg])
{% endcodeblock %}
```

feat(highlight): support caption when wrap is disabled

---

lib/decode_url.js
lib/encode_url.js

[`unescape()`](https://nodejs.org/api/querystring.html#querystring_querystring_unescape_str) is a safer alternative that doesn't throw error when encounter malformed URI.

refactor(encode/decode_url): replace decodeURI with unescape

---

README.md
lib/spawn.js
test/spawn.spec.js

current example uses string argument, so `spawn()` should support it.
also add array argument and options example.

fix(spawn): support string argument

---

lib/highlight.js
test/highlight.spec.js

``` yml
highlight:
tab_replace: '  '
wrap: false
```
``` js
{% codeblock lang:js mark:2,5 %}
const input = [
{ name: 'lorem', item: 'ipsum' },
{ name: 'per', item: 'doming' },
{ name: 'dolor', item: 'lorem' },
{ name: 'usu', item: 'pericula' }
]
{% endcodeblock %}
```

feat(highlight): support 'tab' & 'mark' when wrap is disabled

---

README.md
lib/prism.js
test/prism.spec.js

Feature requested in https://github.com/hexojs/hexo/issues/4460 by @jerryc127

feat(prism): caption

---

lib/highlight.js
lib/prism.js
test/highlight.spec.js
test/prism.spec.js

- BREAKING CHANGE: `<figcaption>` is replaced with `<div>` when wrap is disabled
- https://github.com/hexojs/hexo-util/pull/227#issuecomment-673347477
Affects users of following config:
``` yml
highlight:
line_number: false
wrap: false
prismjs:
enable: true
```
New rendered html:
``` html
<pre>
<div class="caption">
caption here
</div>
<code>codeblock</code>
<pre>
```
suggested css:
``` css
pre div.caption {
font-size: 0.9em;
color: #888;
}
pre div.caption a {
float: right;
}
```

fix(highlight): use <div> when wrap is disabled

---

package.json

https://github.com/hexojs/hexo-util/pull/227 https://github.com/hexojs/hexo-util/pull/229

release: 2.4.0

---

lib/strip_html.js
package.json
test/strip_html.spec.js

`striptags` is **the most safe** strip HTML lib (as it implements a AST parser instead of using regex).
However:
- `striptags` implements a simple Symbol polyfill that Hexo doesn't need (we target latest Node.js LTS)
- `striptags` supports stream and many other features (like tags whitelist) that Hexo doesn't need as well
- In order to supports those features `striptags` introduce a bit performance drawback.
The PR re-implements the `striptags` without those unneeded features. The unit test cases are adopted from `striptags`.

refactor(strip_html): remove striptags deps

---

lib/highlight.js
lib/prism.js
test/highlight.spec.js

Issue resolved: https://github.com/hexojs/hexo/issues/4726

fix(highlight): highlight sublanguages with tab

---

lib/cache.js

As Node.js 10 has been dropped.

refactor(cache): remove Object.fromEntries ponyfill

---

lib/strip_html.js
test/strip_html.spec.js

stripHTML should be more strict with non string

---

.nycrc.yml
test/prism.spec.js

test: fix generate coverage report & test failure when not supported language with Prismjs

---

lib/toc_obj.js

`getText` function is duplicated in [domutils@v2.7.0](https://github.com/fb55/domutils/releases/tag/v2.7.0). Use `textContent` instead of it.
> https://github.com/fb55/domutils/commit/2cf08148dbe02f4c858b78efce34d07fb6f4b5bd#diff-8cdb5d3024cfa8506c5bb07b6975d6c983078bc51c7c166cf9550f47de24027aR36

refactor: use `textContent` instead of `getText`

---

README.md

docs: delete `dependencies badges` from README

---

lib/index.js

[`HashStream` has long been drop](https://github.com/hexojs/hexo-util/pull/198), and we should remove the export for it.

refactor(hash): remove the export of HashStream

---

test/prism.spec.js

https://github.com/hexojs/hexo-util/blob/master/lib/prism.ts#LL57-L65C2
```
interface Options {
caption?: string;
firstLine?: number;
isPreprocess?: boolean;
lang?: string;
lineNumber?: boolean;
mark?: string;
tab?: string;
}
```

fix(prism): use correct type to pass test

---

package.json
tsconfig.json

[refactor: fix TS2550 - add lib es2020, es2019](https://github.com/hexojs/hexo-util/commit/2960b2173efbe2f2343237d557e65ee8d3fddb82)
Property 'fromEntries' does not exist on type 'ObjectConstructor'
Property 'matchAll' does not exist on type 'string'
fixed failure build in node `14` with typescript `5`

fix TS2550 - add lib es2020, es2019

---

lib/escape_html.ts
test/escape_html.spec.js

Fix https://github.com/hexojs/hexo-renderer-marked/issues/229

fix(escape_html): avoid double escape

---

lib/permalink.ts
test/permalink.spec.js

Fix https://github.com/hexojs/hexo/issues/5263

fix(permalink): handle invalid permalink setting

---

tsconfig.json

if use `"include": ["lib/index.ts"]`, `tsc -b --watch` can't detect others files in `lib/` and rebuild.

build(tsc): fix tsconfig for `tsc -b --watch`

---

lib/encode_url.ts
test/encode_url.spec.ts

fix(encodeURL): correct URL search parameter encoding
